name: Build

on:
  push:
    branches:
      - dev
      - release
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - dev
      - release
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
          
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.*
    - name: Install dependencies
      run: |
        dotnet clean ${{ matrix.sln }} -c Release && dotnet nuget locals all --clear
        dotnet restore ${{ matrix.sln }}
    - name: Build
      run: dotnet build ${{ matrix.sln }} -c Release --no-restore /p:GeneratePackageOnBuild=false
    - name: Test
      run: dotnet test ${{ matrix.sln }} -c Release --no-build
